package: wenns_sein_muss
version: '0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wenns_sein_muss


requires:
    php:
        version: '^8'
    redaxo: ^5.13
    packages:
        yform: "^4"



page:
    title: translate:wenns_sein_muss_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    wenns_sein_muss:
        title: translate:wenns_sein_muss_title

        block: system
        prio: 15
        icon: rex-icon fa-check-sign
        perm: wenns_sein_muss[]
        subpages:
            table:
                title: translate:wenns_sein_muss_table
                icon: rex-icon fa-check-sign
                itemclass: pull-right
                perm: admin
            settings:
                title: translate:wenns_sein_muss_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:wenns_sein_muss_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: wenns_sein_muss[docs]

default_config:
    privacy_policy_id: 1
    imprint_id: 1
