package: wenns_sein_muss
version: '5.0.2'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wenns_sein_muss

requires:
    php:
        version: '>=8.2,<9'
    redaxo: ^5.17
    packages:
        yform: "^4.1"
        yform/manager: "^4.1"
        yform_field: "^2.6"

page:
    title: translate:wsm_title
    icon: rex-icon fa-check

pages:
    service:
        title: translate:wsm_service
        icon: rex-icon fa-check
        perm: admin
    group:
        title: translate:wsm_group
        icon: rex-icon fa-asterisk
        perm: admin
    iframemanager:
        title: translate:wsm_iframe
        icon: rex-icon fa-play-circle-o
        perm: admin
    protocol:
        title: translate:wsm_protocol
        icon: rex-icon fa-user
        perm: admin
    revision:
        title: translate:wsm_revision
        icon: rex-icon fa-history
        perm: admin
    docs:
        title: translate:wsm_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemClass: pull-right
        perm: wsm[docs]
    settings:
        title: translate:wsm_settings
        icon: rex-icon fa-gear
        itemClass: pull-right
        perm: admin
        subpages:
            basic:
                title: translate:wsm_settings_basic
                icon: rex-icon fa-gear
                perm: admin
            consent:
                title: translate:wsm_settings_consent
                icon: rex-icon fa-eye
                perm: admin
            text:
                title: translate:wsm_settings_text
                icon: rex-icon fa-font
                perm: admin
            iframe:
                title: translate:wsm_settings_iframe
                icon: rex-icon fa-code
                perm: admin
            demo:
                title: translate:wsm_demo
                perm: admin

default_config:
    #settings page: basic
    revision: "2024-08-31 00:00:00"
    lastchange: "2024-08-31 00:00:00"
    auto_lang: 1
    iframemanager: 1
    disable_page_interaction: 0
    first_install: 1

    # settings page: consent
    consent_modal_title: Diese Webseite verwendet Cookies und Drittanbieter-Dienste
    consent_modal_description: Cookies und vergleichbare Technologien werden verwendet, um den Betrieb der Website wie gewünscht zu ermöglichen. Mit Ihrer Einwilligung werden Inhalte von Drittanbietern und Partnern angezeigt, z.B. Videos, und Zugriffe auf unsere Website analysiert. Dabei werden technisch bedingt Informationen zu Ihrer Verwendung unserer Website an unsere Partner weitergegeben, die diese Informationen möglicherweise mit weiteren Daten zusammenführen.
    consent_modal_settings: Einstellungen öffnen
    consent_modal_accept_all: Alle akzeptieren
    consent_modal_accept_necessary: Nur notwendige akzeptieren

    consent_modal_layout: cloud
    consent_modal_position: bottom center
    consent_modal_swap_buttons: 1
    consent_settings_layout: box

    consent_modal_open: Einstellungen öffnen
    consent_settings_open: Einstellungen öffnen

    # settings page: text
    consent_settings_title: Einstellungen
    consent_settings_save: Speichern
    consent_settings_accept_all: Alle akzeptieren
    consent_settings_reject_all: Alle ablehnen
    consent_settings_close: Schließen
    consent_settings_service_counter_badge: Dienst|Dienste
    
    consent_settings_cookie_table_headers_col1: Name
    consent_settings_cookie_table_headers_col2: Domain
    consent_settings_cookie_table_headers_col3: Ablauffrist
    consent_settings_cookie_table_headers_col4: Beschreibung

    consent_info_domain: Einwilligungs-Protokoll
    consent_info_uuid: Ihre Einwilligungs-ID (für Rückfragen)
    consent_info_unknown: Noch keine Einwilligung erteilt
    consent_info_datestamp: Eingewilligt am...
    consent_info_update_datestamp: Einwilligung zuletzt erneuert am...
    consent_info_more: Weitere Informationen

    # settings page: iframe
    iframe_notice: Diese Inhalte werden von %s zur Verfügung gestellt. Es gelten die Nutzungsbedingungen und Datenschutzbestimmungen des Anbieters.
    iframe_notice_more: Weitere Informationen
    iframe_load_btn: Diesmal anzeigen
    iframe_load_all_btn: Immer anzeigen

# Diese werden in den Einstellungen mit der Sprog-Option eingespielt 
sprog_config:
    # settings page: consent
    consent_modal_title: true
    consent_modal_description: true
    consent_modal_settings: true
    consent_modal_accept_all: true
    consent_modal_accept_necessary: true

    consent_modal_open: true
    consent_settings_open: true

    # settings page: text
    consent_settings_title: true
    consent_settings_save: true
    consent_settings_accept_all: true
    consent_settings_reject_all: true
    consent_settings_close: true
    consent_settings_service_counter_badge: true
    
    consent_settings_cookie_table_headers_col1: true
    consent_settings_cookie_table_headers_col2: true
    consent_settings_cookie_table_headers_col3: true
    consent_settings_cookie_table_headers_col4: true

    consent_info_domain: true
    consent_info_uuid: true
    consent_info_unknown: true
    consent_info_datestamp: true
    consent_info_update_datestamp: true
    consent_info_more: true

    # settings page: iframe
    iframe_notice: true
    iframe_notice_more: true
    iframe_load_btn: true
    iframe_load_all_btn: true
