package: wenns_sein_muss
version: '0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wenns_sein_muss


requires:
    php:
        version: '^8'
    redaxo: ^5.13
    packages:
        yform: "^4"



page:
    title: translate:wenns_sein_muss_title
    prio: 100
    icon: rex-icon rex-icon-check

pages:
    entry:
        title: translate:wenns_sein_muss_entry
        icon: rex-icon rex-check-sign
        perm: admin
    group:
        title: translate:wenns_sein_muss_group
        icon: rex-icon rex-check-sign
        perm: admin
    docs:
        title: translate:wenns_sein_muss_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: wenns_sein_muss[docs]
    settings:
        title: translate:wenns_sein_muss_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin

default_config:
    privacy_policy_id: 1
    imprint_id: 1
    auto_lang: true
    force_consent: false
