package: wenns_sein_muss
version: '3.0.0-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wenns_sein_muss

requires:
    php:
        version: '^8'
    redaxo: ^5.13
    packages:
        yform: "^4"

page:
    title: translate:wenns_sein_muss_title
    icon: rex-icon fa-check

pages:
    consent:
        title: translate:wenns_sein_muss_service
        icon: rex-icon fa-check
        perm: admin
        subpages:
            service:
                title: translate:wenns_sein_muss_service
                icon: rex-icon fa-check
                perm: admin
            group:
                title: translate:wenns_sein_muss_group
                icon: rex-icon fa-asterisk
                perm: admin
            protocol:
                title: translate:wenns_sein_muss_protocol
                icon: rex-icon fa-user
                perm: admin
    domain:
        title: translate:wenns_sein_muss_domain
        icon: rex-icon fa-gear
        perm: admin
    docs:
        title: translate:wenns_sein_muss_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: wenns_sein_muss[docs]
    settings:
        title: translate:wenns_sein_muss_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
        subpages:
            basic:
                title: translate:wenns_sein_muss_settings_basic
                icon: rex-icon fa-gear
                perm: admin
            consent:
                title: translate:wenns_sein_muss_settings_consent
                icon: rex-icon fa-eye
                perm: admin
            text:
                title: translate:wenns_sein_muss_settings_text
                icon: rex-icon fa-font
                perm: admin
            iframe:
                title: translate:wenns_sein_muss_settings_iframe
                icon: rex-icon fa-code
                perm: admin
            demo:
                title: translate:wenns_sein_muss_demo
                perm: admin

default_config:
    #settings page: basic
    revision: 0
    auto_lang: 1
    force_consent: 1
    iframemanager: 1
    disable_page_interaction: 0

    # settings page: consent
    consent_modal_title: We use cookies!
    consent_modal_description: Hi, this website uses essential cookies
    consent_modal_primary_btn: Accept all
    consent_modal_secondary_btn: Reject all

    consent_modal_layout: cloud
    consent_modal_position: bottom center
    consent_modal_swap_buttons: true
    settings_modal_layout: box

    # settings page: text
    settings_modal_title: Einstellungen
    settings_modal_save_settigns_btn: speichern
    settings_modal_accept_all_btn: Alle akzeptieren
    settings_modal_reject_all_btn: Alle ablehnen
    settings_modal_close_btn_label: Schließen
    settings_modal_service_counter_label: Dienst|Dienste
    
    settings_modal_cookie_table_headers_col1: Name
    settings_modal_cookie_table_headers_col2: Domain
    settings_modal_cookie_table_headers_col3: Ablauffrist
    settings_modal_cookie_table_headers_col4: Beschreibung

    settings_modal_block_consent_title: Einwilligungs-Protokoll
    settings_modal_block_more_title: Weitere Informationen
    settings_modal_block_more_description: 'For any queries in relation to our policy on cookies and your choices, please <a class="cc-link" href="#yourcontactpage">contact us</a>'

    # settings page: iframe
    iframe_notice: Html <b>notice</b> message
    iframe_load_btn: Diesmal anzeigen
    iframe_load_all_btn: Immer anzeigen

    # consent_info_domain: Ihre Einwilligung trifft auf die folgenden Domains zu
    # consent_info_consented: Ihre aktuell gewählten Einstellungen
    # consent_info_uuid: Ihre Einwilligungs-ID (für Rückfragen)
    # consent_info_datestamp: Eingewilligt am...
    # consent_info_open_settings: Einstellungen öffnen
